### ISSUE TITLE
ld

### ISSUE THREAD

**Issue by fgsoftware1** [fgsoftware1/calculator-yacc-lex#3]
/usr/bin/ld: cannot find -lfl

**Comment by circutrider21** [comment]
Some systems make libfl a separate package from flex, as it is rarely needed. The libfl library just contains two functions:

int main() {
    while (yylex());
    return 0;
}

int yywrap() {
    return 1;
}
Normally you'll want your own main function rather than the one from libfl, and defining yywrap yourself is trivial. Alternately, you can use %option noyywrap and not need it at all.

In your case, try just getting rid of the -lfl option. If you get an error about yywrap, add
%option noyywrap to the first section of your test.lex file.

**Comment by fgsoftware1** [comment]
> Some systems make libfl a separate package from flex, as it is rarely needed. The libfl library just contains two functions:
> 
> ```
> 
> int main() {
>     while (yylex());
>     return 0;
> }
> 
> int yywrap() {
>     return 1;
> }
> ```
> 
> Normally you'll want your own main function rather than the one from libfl, and defining yywrap yourself is trivial. Alternately, you can use %option noyywrap and not need it at all.
> 
> In your case, try just getting rid of the -lfl option. If you get an error about yywrap, add %option noyywrap to the first section of your test.lex file.

/usr/bin/ld: /tmp/ccjJfM4i.o: in function `yyparse':
y.tab.c:(.text+0x323): undefined reference to `yylex'
